import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { ThemeProvider } from "@/components/providers/theme-provider";
import { cn } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord cua bo may",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body className={
          cn(geistSans.variable, geistMono.variable,
          "bg-white dark:bg-[#313338] text-black dark:text-white")
        }>
          <ThemeProvider attribute={"class"} defaultTheme="dark"
            enableSystem={true}
            storageKey="discord-cua-bo-may-theme">
              {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
